<?php

	register_field_group(array (
			'id' => 'acf_quizy',
			'title' => 'Quizy',
			'fields' => array (
				array (
					'key' => 'field_55376e01e84f0',
					'label' => 'Pytania',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_55376e2ae84f1',
					'label' => 'Pytania',
					'name' => 'questions',
					'type' => 'repeater',
					'required' => 1,
					'sub_fields' => array (
						array (
							'key' => 'field_55376e40e84f2',
							'label' => 'Pytanie',
							'name' => 'question',
							'type' => 'textarea',
							'required' => 1,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'required' => 1,
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_55376e59e84f3',
							'label' => 'Odpowiedź A',
							'name' => 'a',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'required' => 1,
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_55376e6ae84f4',
							'label' => 'Odpowiedź B',
							'name' => 'b',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'required' => 1,
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_55376e6fe84f5',
							'label' => 'Odpowiedź C',
							'name' => 'c',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'required' => 1,
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_55376e78e84f6',
							'label' => 'Odpowiedź D',
							'name' => 'd',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'required' => 1,
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_55376e83e84f7',
							'label' => 'Prawidłowa odpowiedź',
							'name' => 'correct_answer',
							'type' => 'select',
							'required' => 1,
							'column_width' => '',
							'choices' => array (
								'a' => 'Odpowiedź A',
								'b' => 'Odpowiedź B',
								'c' => 'Odpowiedź C',
								'd' => 'Odpowiedź D',
								'' => '',
							),
							'default_value' => '',
							'allow_null' => 0,
							'multiple' => 0,
						),
					),
					'row_min' => 1,
					'row_limit' => 20,
					'layout' => 'row',
					'button_label' => 'Dodaj pytanie',
				),
				array (
					'key' => 'field_55376f830bd17',
					'label' => 'Krótki opis',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53489bd653118',
					'label' => 'Krótki opis',
					'name' => 'excerpt',
					'type' => 'wysiwyg',
					'required' => 1,
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'no',
				),
				array (
					'key' => 'field_553770029a722',
					'label' => 'Powiązane zasoby',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_55376fd59a721',
					'label' => 'Powiązane zasoby',
					'name' => 'related_items',
					'type' => 'relationship',
					'return_format' => 'object',
					'post_type' => array (
						0 => 'pdf',
						1 => 'quiz',
						2 => 'event',
						3 => 'ebook',
						4 => 'link',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'filters' => array (
						0 => 'search',
						1 => 'post_type'
					),
					'result_elements' => array (
						0 => 'featured_image',
						1 => 'post_type',
						2 => 'post_title',
					),
					'max' => 5,
				),
				array (
					'key' => 'field_553771588dd07',
					'label' => 'Próg zaliczający',
					'name' => 'percange_to_pass_quiz',
					'type' => 'tab',
				),
				array (
					'key' => 'field_553771608dd08',
					'label' => 'Próg zaliczający quiz (w procentach)',
					'name' => 'percange_to_pass_quiz',
					'type' => 'number',
					'required' => 1,
					'default_value' => 75,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '100',
					'step' => 1,
				),
				array (
					'key' => 'field_553450029a722',
					'label' => 'Zasoby do wygrania',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_554866fd59a721',
					'label' => 'Zasoby',
					'name' => 'resources_to_win',
					'type' => 'relationship',
					'return_format' => 'id',
					'required' => 1,
					'post_type' => array (
						0 => 'pdf',
						1 => 'quiz',
						3 => 'event',
						4 => 'link',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'filters' => array (
						0 => 'search',
						1 => 'post_type',
					),
					'result_elements' => array (
						0 => 'featured_image',
						1 => 'post_type',
						2 => 'post_title',
					),
					'max' => 15,
				)
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'quiz',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));